POST http://localhost:3000/comment
Content-Type: application/json

{
  "post_id": "6974af7ce5adc749ab67a553",
  "user_id": 1,
  "comment": "Bla Bla 4"
}

###
GET http://localhost:3000/comment

###
GET http://localhost:3000/comment/6974af64e5adc749ab67a551

###
DELETE http://localhost:3000/comment/6

###
PUT http://localhost:3000/comment/2
Content-Type: application/json

{
    "comment": "changed!!!!!"
}

