POST http://localhost:3000/comment
Content-Type: application/json

{
  "comment_id": 6,
  "post_id": 4,
  "comment": "liron"
}

###
GET http://localhost:3000/comment

###
GET http://localhost:3000/comment/1

###
DELETE http://localhost:3000/comment/6

###
PUT http://localhost:3000/comment/2
Content-Type: application/json

{
    "comment": "changed!!!!!"
}

