###
GET http://localhost:3000/post

###
POST http://localhost:3000/post
Content-Type: application/json

{
    "post_id": 9,
    "sender_id": 6
}
###
GET http://localhost:3000/post/3

###
PUT http://localhost:3000/post/1
Content-Type: application/json

{
    "sender_id": 55
}

###
DELETE http://localhost:3000/post/3