POST http://localhost:3000/comment
Content-Type: application/json

{
  "post_id": "69765d8b24a38a96a527e8e9",
  "user_id": "69765c5124a38a96a527e8e0",
  "comment": "Bla Bla 1"
}

###
GET http://localhost:3000/comment

###
GET http://localhost:3000/comment/6974af64e5adc749ab67a551

###
DELETE http://localhost:3000/comment/6

###
PUT http://localhost:3000/comment/2
Content-Type: application/json

{
    "comment": "changed!!!!!"
}

